apiVersion: apps/v1
kind: Deployment
metadata:
  name: santosh-deploy
  labels:
    app: santosh-banking-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: santosh-banking-app
  template:
    metadata:
      labels:
        app: santosh-banking-app
    spec:
      containers:
      - name: santosh-banking-container
        image: dskdockerid/santoshbankimage:latest
        ports:
        - containerPort: 8081		
---
apiVersion: v1
kind: Service
metadata:
  name: santosh-service
  labels:
    app: santosh-banking-app
spec:
  selector:
    app: santosh-banking-app

  type: NodePort
  ports:
  - nodePort: 32001
    port: 8081
    targetPort: 8081
